#!/usr/bin/env bash
# Fix ImportError: libcudart.so.13 (vLLM CUDA-13 wheels need runtime on LD_LIBRARY_PATH)

setup_cuda_ld_path() {
  local venv="${VERATHOS_DIR}/.venv-vllm"
  local helper="${VERATHOS_DIR}/.vllm_ld_path.sh"

  [[ -d "$venv" ]] || {
    warn "vLLM venv not found yet at ${venv} — CUDA path helper will be written after setup_miner"
    return 0
  }

  log "Ensuring CUDA 13 runtime + LD_LIBRARY_PATH helper..."

  # Install into the venv so libcudart.so.13 is discoverable
  if [[ -x "${venv}/bin/pip" ]]; then
    "${venv}/bin/pip" install --quiet --no-cache-dir 'nvidia-cuda-runtime==13.0.96' || \
      warn "nvidia-cuda-runtime install failed (may already be on system site-packages)"
  fi

  cat > "$helper" <<EOF
# Auto-generated by verathos_installer — NVIDIA pip libs for vLLM dynamic linker
_VENV="${venv}"
# shellcheck disable=SC1091
source "\${_VENV}/bin/activate"
export LD_LIBRARY_PATH="\$(
"\${_VENV}/bin/python" - <<'PY'
import glob, os, site
dirs = []
for sp in site.getsitepackages():
    dirs += glob.glob(os.path.join(sp, "nvidia", "*", "lib"))
# Also pick up system site-packages when venv uses --system-site-packages
for sp in ("/usr/local/lib/python3.12/dist-packages", "/usr/lib/python3/dist-packages"):
    dirs += glob.glob(os.path.join(sp, "nvidia", "*", "lib"))
try:
    import torch
    dirs.append(os.path.join(os.path.dirname(torch.__file__), "lib"))
except Exception:
    pass
print(":".join(d for d in sorted(set(dirs)) if os.path.isdir(d)))
PY
)\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
EOF

  # Validate import if GPU libs are present
  # shellcheck disable=SC1090
  if source "$helper" && "${venv}/bin/python" -c "import vllm._C" 2>/dev/null; then
    ok "vllm._C imports successfully with LD_LIBRARY_PATH"
  else
    warn "Could not verify vllm._C import yet (GPU/driver may be unavailable in this shell). Helper written to ${helper}"
  fi
}
